[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/auth/confirm"
  to = "/auth/confirm/"
  status = 200

[[redirects]]
  from = "/auth/reset-password"
  to = "/auth/reset-password/"
  status = 200

[[redirects]]
  from = "/share/*"
  to = "/share/"
  status = 200
